# This is a basic workflow to help you get started with Actions




name: Build and Release Apps
on:
  push:
    branches:
      - master
    # Triggers the workflow on push or pull request events but only for the tagged

jobs:

  very-good-analytics:
    name: analytics
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example/flutter_example
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get

      - name: analytics
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: example/flutter_example/coverage/lcov.info
          min_coverage: 10
